name: Windows

on:
  workflow_call:

jobs:
  benchmark:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\scripts\benchmark.bat --transfer-count=4000

  c_sample:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\scripts\install_zig.bat
      - run: .\zig\zig build c_sample

  repl_integration:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\scripts\install.bat
      - run: .\zig\zig build repl_integration
      - run: .\zig-out\bin\repl_integration.exe
